var _oIntpl,cINTPL;
function $(n){return document.getElementById(n)}
function INTPL(){var r="",a=arguments,l=a.length,f,c,i;if(!_oIntpl) _oIntpl=new cINTPL();if(l){f="call@"+a[0]+"#"+l;if(!_oIntpl[f]&&_oIntpl[a[0]]){c="return this."+a[0]+"(";for(i=1;i<l;i++) c+=(i!=1?",":"")+"a["+i+"]";c+=")";_oIntpl[f]=new Function("a",c);}if(_oIntpl[f]) r=_oIntpl[f](a);}else{r=_oIntpl.version;}return r;}
cINTPL=function(){this.version="1.0.70807";this.oAd=-1;this.sEl="";this._Ss="%3Cscript%20type%3D%22text%2Fjavascript%22%3E%0D%0A%3C%21--%20%3C%21%5BCDATA%5B%0D%0A";this._Se="%0D%0A%2F%2F%20%5D%5D%3E%20--%3E%0D%0A%3C%2Fscript%3E";this.className="cINTPL";this._pDf="location=no,menubar=no,toolbar=no,resizable=no,";this._bUa=navigator.userAgent.toLowerCase();this._bOp=(this._bUa.indexOf("opera")!=-1?true:false);this._bIe=(this._bUa.indexOf("msie")!=-1&&!this._bOp?true:false);this._bIe4=(this._bIe&&(this._bUa.indexOf("msie 2.")!=-1||this._bUa.indexOf("msie 3.")!=-1||this._bUa.indexOf("msie 4.")!=-1)&&!this._bOp?true:false);this._bKh=(this._bUa.indexOf("khtml")!=-1?true:false);this._bGe=(this._bUa.indexOf("gecko")!=-1&&!this._bKh?true:false);this._bN4=(document.layers?true:false);this._bMc=(this._bUa.indexOf("mac")!=-1?true:false);}
function _g_write_pebi(){if(typeof(Error)!='undefined')eval('try{var d=document,b=d.body,s;if(d.createElement&&b.appendChild&&(s=d.createElement("SCRIPT"))){s.type="text/javascript";s.src=location.protocol+"//interia.hit.gemius.pl/_"+(new Date()).getTime()+"/pbi_pe.js?id=7cd@ueKbjLizL8tsiGI3vPf7";b.appendChild(s);}}catch(e){}');}
cINTPL.prototype.g_write_pebi=function(){var w=window;if(this.isGecko()&&w.addEventListener) w.addEventListener("load",_g_write_pebi,false);else if(this.isOpera()&&w.attachEvent) w.attachEvent("onload",_g_write_pebi);else document.write('<scr'+'ipt type="text/javascript" src="'+location.protocol+'//interia.hit.gemius.pl/_'+(new Date()).getTime()+'/pbi_pe.js?id=7cd@ueKbjLizL8tsiGI3vPf7" defer="defer"></scr'+'ipt>');}
cINTPL.prototype.g_parameters_g=function(){var url=new String(),d=document,s;if(d.URL) url+='&href='+escape(d.URL);if(d.referrer) url+='&ref='+escape(d.referrer);if(window.screen){s=screen;if(s.width) url+='&screen='+s.width+'x'+s.height;if(s.colorDepth) url+='&col='+s.colorDepth;}if(d.all||d.layers) url+='&java='+navigator.javaEnabled();return url;}
if(!g_parameters_g){var g_parameters_g=cINTPL.prototype.g_parameters_g;}
cINTPL.prototype.setRef = function(u){return u+escape((u.indexOf('?')==-1?'?':'&')+'ref_sr='+document.location.host);}
cINTPL.prototype.getCookie=function(n){var r=null,a=n+"=",b=a.length,c=document.cookie,l=c.length,i=0,j,e;while(i<l){j=i+b;if(c.substring(i,j)==a){e=c.indexOf(";",j);if(e==-1)e=c.length;r=unescape(c.substring(j,e));break;}i=c.indexOf(" ",i)+1;if(i==0)break;}return r;}
cINTPL.prototype.setCookie=function(n,v,e,p,d,s){document.cookie=n+"="+escape(v)+";"+(e?"expires="+new Date((new Date()).getTime()+e*1000).toGMTString()+";":"")+(p?"path="+p+";":"")+(d?"domain="+d+";":"")+(s?"; secure":"");}
cINTPL.prototype.goUrl=function(u,n){if(n)this.openWindow(u,n); else window.location.href=u;}
cINTPL.prototype.makePopup=function(o,n,w,h,e){if (o&&o.href&&o.href.indexOf("javascript")==-1) o.href="javascript:void (window.open('"+o.href+"'"+(n?",'"+n+"'":"")+(w||h||e?(n?"":",null")+",'"+(w?"width="+w+",":"")+(h?"height="+h+",":"")+this._pDf+(e?e+",":"")+"status=yes'":"")+")).focus()";}
cINTPL.prototype.openWindow=function(u,n,w,h,e){var r=this.createWindow(u,n,w,h,e);if(r)r.focus();}
cINTPL.prototype.openPopup=function(u,n,w,h,e){var r=this.createWindow(u,n,w,h,this._pDf+(e?","+e:""));if(r)r.focus();}
cINTPL.prototype.createWindow=function(u,n,w,h,e){var r=null;if (w||h||e)r=window.open(u,n||null,(w?"width="+w+",":"")+(h?"height="+h+",":"")+(e?e+",":"")+"status=yes");else r=window.open(u,n||null);return r;}
cINTPL.prototype.get=function(n){var r=null;if(this[n]&&typeof(this[n])!='function') r=this[n];return r;}
cINTPL.prototype.set=function(n,v){var r=false;if (n!="version"&&n!="className"&&(!this[n]||(this[n]&&typeof(this[n])!='function'))){this[n]=v;r=true;}return r;}
cINTPL.prototype.urlEncode=function(s){s=""+s;s=s.replace(/\%/g,"%25");s=s.replace(/\s/g,"%20");s=s.replace(/\#/g,"%23");s=s.replace(/\&/g,"%26");s=s.replace(/\+/g,"%2B");s=s.replace(/\?/g,"%3F");s=s.replace(/\"/g,"%22");s=s.replace(/\'/g,"%27");s=s.replace(/:/g,"%3A");s=s.replace(/\//g,"%2F");s=s.replace(/</g,"%3C");s=s.replace(/>/g,"%3E");s=s.replace(/\\/g,"%5C");return s;}
cINTPL.prototype.isIe=function(){return this._bIe;}
cINTPL.prototype.isOldIe=function(){return this._bIe4;}
cINTPL.prototype.isOpera=function(){return this._bOp;}
cINTPL.prototype.isGecko=function(){return this._bGe;}
cINTPL.prototype.isOldNetscape=function(){return this._bN4;}
cINTPL.prototype.isMac=function(){return this._bMc;}
cINTPL.prototype.isLinux=function(){return (this._bUa.indexOf("linux")!=-1) }
cINTPL.prototype.isKhtml=function(){return this._bKh;}
cINTPL.prototype.getMail=function(){var r=this.getCookie("IPLWWWID"),b=this.getCookie("IPLWWWIDB"),c=this.getCookie("VAST");if(r&&!b)r=(escape(r+"")).replace("%26%230064%3B","@");if(c&&r&&r.indexOf('@')!=-1)return r;else return false;}
cINTPL.prototype.getIdent=function(){var r=this.getCookie("ZNWWWID"),b=this.getCookie("IPLWWWIDB"),c=this.getCookie("ZNVAST");if(c&&r&&(!b||b&&document.location.hostname.indexOf("znajomi")!=-1)){if(!b){r=(escape(r+"")).replace("%26%230064%3B","@");}else{r=r.replace("<","&lt;");r=r.replace(">","&gt;");r=r.replace("&#0064;","@");}}else{return false;}return r;}
cINTPL.prototype.writeLogout=function(a,b){var m=this.getMail();if(m)document.write((a?a:'')+m.substring(0,30)+(m.length>30?'...':'')+' <a href="http://ssl.interia.pl/logout?referer=http://'+document.location.host+'/">wyloguj</a>&nbsp; |'+(b?b:''));}
cINTPL.prototype.getFlashVersion=function(){return flashVersion;}
cINTPL.prototype.isFlash=function(v){v=v||0;return (flashVersion>=v?true:false);}
cINTPL.prototype.write=function(c){document.write(c)}
cINTPL.prototype.insert=function(n,c){$(n).innerHTML=c}
cINTPL.prototype.hitGemius=function(g){(new Image()).src=location.protocol+'//interia.hit.gemius.pl/_'+(new Date()).getTime()+'/redot.gif?l=8&id='+g+INTPL('g_parameters_g');}
cINTPL.prototype.iGstat=function(g){var r=this.Ig;this.Ig=g;g.onload=new Function("INTPL('gStat',1)");g.onerror=new Function("INTPL('gStat',0)");return r;}
cINTPL.prototype.gStat=function(v){var i=this.Ig;if(i){i.onerror=i.onload=null;if(v&&i.width&&i.width>1)this.AddOnload(this.wStat);}}
cINTPL.prototype.wStat=function(){if(typeof(Error)!='undefined')eval('try{var d=document,b=d.body,s;if(d.createElement&&b.appendChild&&(s=d.createElement("script"))){s.type="text/javascript";s.src=location.protocol+"//interia.hit.gemius.pl/_"+(new Date()).getTime()+"/pbi_pe.js?id=7cd@ueKbjLizL8tsiGI3vPf7";b.appendChild(s);}}catch(e){}');}
cINTPL.prototype.AddOnload=function(f){if(INTPL('isIe')&&INTPL('isOldIe')){window.onload=ReadOnload;olArray[olArray.length]=f;}else if(window.onload){if(window.onload!=ReadOnload){olArray[0]=window.onload;window.onload=ReadOnload;}olArray[olArray.length]=f;}else window.onload=f;}
var AddOnload=cINTPL.prototype.AddOnload;
function ReadOnload(){for(var i=0;i<olArray.length;i++)olArray[i]();}
cINTPL.prototype.adspace=function(n){if(ad_spaces[n]){if(ad_spaces[n].indexOf('+ rand +')!=-1)eval('ad_spaces[\''+n+'\']=\''+ad_spaces[n]+'\';');if(document.getElementById&&ad_spaces[n].indexOf('c.adsv')!=-1&&ad_spaces[n].indexOf('obj_'+n)!=-1)ad_spaces[n]=ad_spaces[n]+'<scr'+'ipt type="text/javascript">garr=/(gda[^=]*)=([^ "]*)/.exec(ad_spaces["'+n+'"]);document.getElementById("obj_'+n+'").SetVariable(unescape(garr[1]),unescape(garr[2]));</scr'+'ipt>';}}
cINTPL.prototype.adspaces=function(){if(ad_spaces['gora_srodek_popup'])ad_spaces['gora_srodek']=ad_spaces['gora_srodek_popup'];if(ad_spaces['gora_srodek']){if(ad_spaces['gora_srodek'].indexOf('adMegaBanner')!=-1){adMegaBanner=true;ad_spaces['gora_srodek']=ad_spaces['gora_srodek'].replace('adMegaBanner','');}else if(ad_LSB&&ad_PSB)ad_spaces['gora_srodek']='<table'+ad_TLO+' id="ad2layer" align="center" width="760" border="0" cellspacing="0" cellpadding="0"><tr><td colspan="4" style="font-size:1px;line-height:1px;">&nbsp;</td></tr><tr><td width="6" style="font-size:1px;line-height:1px;">&nbsp;</td><td width="126" align="right" valign="middle">'+ad_LSB+'</td><td width="476" align="center" valign="middle">'+ad_spaces['gora_srodek']+'</td><td width="140" valign="middle">'+ad_PSB+'</td></tr><tr><td colspan="4" style="font-size:1px;line-height:1px;">&nbsp;</td><td width="6" style="font-size:1px;line-height:1px;">&nbsp;</td></tr></table>';}if(ad_spaces['gora_srodek_2_sgl']&&ad_spaces['gora_srodek_2_sgl'].indexOf('adMegaBanner')!=-1)ad_spaces['gora_srodek_2_sgl']=ad_spaces['gora_srodek_2_sgl'].replace('adMegaBanner','');for(p in ad_spaces)this.adspace(p);}
cINTPL.prototype.insertAd=function(n,b,a){if(INTPL("isAd",n)){document.write((b?b:'')+'<div id="ad_'+n+'" align="center">'+ad_spaces[n]+'</div>'+(a?a:''));}}
var insertAd=cINTPL.prototype.insertAd;
cINTPL.prototype.insertAd1024=function(n,t){var d=document,a=["1024_lewy","1024_prawy"],o=0;for(i in a)if(INTPL("isAd",a[i])){d.write('<div id="ad1024_'+a[i]+'" style="display:none;position:absolute;top:133px;left:-300px;width:120px;padding-top:1px;border-top:solid 1px #475C9B">');INTPL("insertAd",a[i]);d.write('</div>');if(!o){o=1;INTPL("AddOnload",new Function("INTPL('runAd1024','"+n+"',"+(parseInt(t)||0)+")"))}}}
cINTPL.prototype.runAd1024=function(n,t){var w=window,mt=$(n),sl=$("ad1024_1024_lewy"),sr=$("ad1024_1024_prawy"),f;if(mt&&(sl||sr)){t=parseInt(t)||0;INTPL('scaleAd1024',n,t);f=new Function("INTPL('scaleAd1024','"+n+"',"+t+")");if(w.addEventListener)w.addEventListener("resize",f,false);else w.attachEvent("onresize",f);}}
cINTPL.prototype.scaleAd1024=function(n,t){var sL=$("ad1024_1024_lewy"),sR=$("ad1024_1024_prawy"),sS=$(n),bW=document.body.clientWidth,wi=0;if(bW&&(sR||sL)){wi=parseInt(sS.width||sS.offsetWidth);t=parseInt(t)||0;if(bW-wi>240){if(sL){sL.style.top=sS.offsetTop+t+"px";sL.style.left=Math.floor((bW-wi)/2)-121+"px";sL.style.display="block";}if(sR){sR.style.top=sS.offsetTop+t+"px";sR.style.left=Math.floor((bW-wi)/2)+wi+1+"px";sR.style.display="block";}}else{if(sL)sL.style.display="none";if(sR)sR.style.display="none";}}}
cINTPL.prototype.rewriteAdSpaces=function(){var p;INTPL("adspaces");for(p in aSpace)if(p!="master"&&aSpace[p])ad_spaces[p]=aSpace[p];}
cINTPL.prototype.rewriteSpaces=function(){var p,c,s;for(p in aSpace)if(p!="master"){c="if(typeof "+unescape(aSpace[p])+"=='function')"+unescape(aSpace[p])+"();";try{s=eval(aSpace[p]+".toString()")}catch(e){s=""}if(s.indexOf('insert bb kontekst')==-1&&(s.indexOf('_a_d_yes__')!=-1||s.indexOf('adserver_emissions')!=-1))ad_spaces[p]=unescape(this._Ss)+c+unescape(this._Se);else{eval(c);ad_spaces[p]=0;}}this.AddOnload(this.hbol)}
cINTPL.prototype.insertMaster=function(){document.write(unescape(this._Ss+aSpace['master']+this._Se))}
cINTPL.prototype.insertMoon=function(){var p,c,f,s;for(p in aSpace)if(p!="master"){f="typeof "+unescape(aSpace[p])+"=='function'";c="if("+f+")"+unescape(aSpace[p])+"();";if(eval(f)){s=eval(aSpace[p]+".toString()");if(s.indexOf('_a_d_yes__')!=-1||s.indexOf('adserver_emissions')!=-1){aSpace[p]=unescape(this._Ss)+c+unescape(this._Se);}else{eval("try{"+c+"}catch(e){}");aSpace[p]=0;}}else aSpace[p]=0;}for(p in mSpace)if(!aSpace[mSpace[p]])ad_PSL+=(ad_PSL?",":"")+mSpace[p];document.write(unescape("%3C")+'script type="text/javascript" src="'+location.protocol+'//'+ad_URL+'?XN=1&CID='+ad_CID+'&PID='+ad_PID+'&PSL='+ad_PSL+(ad_SKY?'&SRC_skyscraper=1':'')+'&PLG='+ad_PLG+ad_SSL+'&RND='+ad_RND+'&RES='+ad_RES+unescape('"%3E%3C/script%3E'));}
cINTPL.prototype.isAd=function(n){return (ad_spaces&&ad_spaces[n]?true:false)}
cINTPL.prototype.getAd=function(n){return (ad_spaces&&ad_spaces[n]?ad_spaces[n]:null)}
cINTPL.prototype.setAd=function(n,c){ad_spaces[n]=c}
cINTPL.prototype.hbol=function(){if(typeof(_hb_prf)=='string'&&typeof(_hb_ids)=='object'){_hb_img=[];var src=location.protocol+'//'+_hb_prf+'hit.gemius.pl/_'+(new Date()).getTime()+'/redot.gif',cnt=0,icnt=0,ids='',id;for(id in _hb_ids){ids+=_hb_ids[id];if((++cnt%5)==0){_hb_img[++icnt]=new Image();_hb_img[icnt].src=src+ids;ids='';}}if(ids!=''){_hb_img[++icnt]=new Image();_hb_img[icnt].src=src+ids;}}}
cINTPL.prototype.hbht=function(prf,id,arg,sarg){_hb_prf=prf;if(!(typeof(_hb_ids)=='object'))_hb_ids=new Array();_hb_ids.push('/id='+id+'/stparam='+arg+'/sarg='+sarg)}
var olArray=[],oFlash=false,cnt=0,FlashMode=0,flashVersion=0,flashInstalled=false,x,n,flashVF,ad_onLoad=0;
if(navigator.plugins&&(n=navigator.plugins).length){for(x=0;x<n.length;x++){if(n[x].name.indexOf('Shockwave Flash')!=-1){flashVF=n[x].description.split('Shockwave Flash ')[1];flashVersion=flashVF.split('.')[0];flashInstalled=true;break;}}}else if(window.ActiveXObject&&typeof(Error)!='undefined'){for(x=2;x<=9;x++){oFlash=false;eval('try{oFlash=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.'+x+'");}catch(e){}');if(oFlash){flashInstalled=true;flashVersion=x;}}}if(flashVersion>=6){FlashMode=3;}else if(flashVersion==5){FlashMode=2;}else if(flashVersion==4){FlashMode=1;}
var ad_spaces=[],ad_RES=(screen.width>=1024?1:0),ad_PLG=((FlashMode==1)?'fla4':(FlashMode==2?'fla4,fla5':(FlashMode==3?'fla4,fla5,fla6':'NOPLG'))),ad_SSL=((location.protocol=='https:')?'&SSL=1':''),ad_RND=Math.floor(5091980*Math.random()),rand=ad_RND,adMegaBanner=false,winwidth=((document.layers)?self.innerWidth:(document.body)?document.body.clientWidth:0),skymainposx=((winwidth/2)+200);
ad_spaces['gora_srodek']=ad_spaces['podmenu_1']=ad_spaces['podmenu_2']=ad_spaces['button_sponsora']=ad_spaces['skyscraper']=ad_spaces['skyscraper_auto']=ad_spaces['gora_srodek_popup']=ad_spaces['news']=ad_spaces['z_banner_440x60']=ad_spaces['podmenu_1']='';
function interMovieStartLoad(){}
function interMovieLoad(){}
