(function(g){var window=this;var z6=function(a){g.X.call(this,{H:"button",ba:["ytp-offline-slate-button","ytp-button"],K:[{H:"div",M:"ytp-offline-slate-button-icon",K:["{{icon}}"]},{H:"div",M:"ytp-offline-slate-button-text",K:["{{text}}"]}]});this.C=a;this.A=this.o=null;this.hide();this.R("click",this.D,this)},Hxa=function(a,b){!a.o&&b&&b.toggleButtonRenderer?a.o=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.o=null);
A6(a)},A6=function(a){if(a.o){if(a.o.isToggled){var b=a.o.toggledText?g.eN(a.o.toggledText):"";
a.update({text:b,icon:Ixa(a.o.toggledIcon)})}else b=a.o.defaultText?g.eN(a.o.defaultText):"",a.update({text:b,icon:Ixa(a.o.defaultIcon)});a.show()}else a.hide()},Ixa=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.TU?{H:"div",ba:["ytp-icon","ytp-icon-notifications-none"]}:{H:"svg",U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{H:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.fV();default:return null}},B6=function(a){g.X.call(this,
{H:"div",
M:"ytp-offline-slate",K:[{H:"div",M:"ytp-offline-slate-bar",K:[{H:"span",M:"ytp-offline-slate-icon",K:[g.TU?{H:"div",ba:["ytp-icon","ytp-icon-live-icon"]}:{H:"svg",U:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{H:"path",U:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{H:"circle",U:{cx:"12",cy:"12",r:"3"}}]}]},{H:"span",M:"ytp-offline-slate-buttons"},{H:"span",M:"ytp-offline-slate-messages",K:[{H:"div",M:"ytp-offline-slate-main-text",K:["{{maintext}}"]},{H:"div",M:"ytp-offline-slate-subtitle-text",K:["{{subtitletext}}"]}]}]},{H:"div",M:"ytp-offline-slate-final-day",K:[{H:"div",M:"ytp-offline-slate-final-day-line-1",K:["Dawn of"]},{H:"div",M:"ytp-offline-slate-final-day-line-2",K:["The Final Day"]},{H:"div",M:"ytp-offline-slate-final-day-line-3",K:["-24 Hours Remain-"]}]}]});
this.A=a;this.B=this.o=null;this.C=new g.Nt(this.F,1E3,this);this.P(a,"presentingplayerstatechange",this.G);this.P(a,"livestatedata",this.D);this.hide();a=this.A.fa();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.D(a)},C6=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.eN(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.eN(b.mainText):"";a.update({maintext:b,subtitletext:d});g.T(a.element,"ytp-offline-slate-single-text-line",!d)}},E6=function(a){g.uU.call(this,a);
this.I=!1;this.J=0;this.G=!1;this.o=window.NaN;this.A=this.B=null;this.C=!1;this.F=null;this.L=-(new g.ao).getTimezoneOffset();this.D=new g.iF(this);g.N(this,this.D);var b=this.g.fa();if(b.wa){var c=g.W(this.g);g.NK()?!c.experiments.g("live_fresca_v2")||!g.zL(c)&&g.yL(c)||(this.I=this.C=!0,this.F=new B6(this.g),g.N(this,this.F),g.oU(this.g,this.F.element,4),(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.A=b.playabilityStatus),this.A?(b=Jxa(this.A.liveStreamability&&this.A.liveStreamability.liveStreamabilityRenderer))?
D6(this,b):D6(this,7500):D6(this,1E3)):g.SS(this.g.app.A,"html5.unsupportedlive","YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1")}this.D.P(a,"heartbeatparams",this.HK);this.D.P(a,"presentingplayerstatechange",this.IK);this.D.P(a,"videoplayerreset",this.TR);this.D.P(a,"crn_heartbeat",this.GK);this.C&&this.A&&Kxa(this,this.A);b=new g.gP(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"});g.hU(a,[b])},Lxa=function(a){a=a.g.fa();
return!!g.rN(a)&&!a.Rr},F6=function(a){var b=a.g.fa();
return Lxa(a)?!!a.B:!!b.heartbeatToken},D6=function(a,b){if(!a.o&&a.I){var c=a.g.fa();
if(F6(a)||c.wa)void 0==b&&(b=a.G?a.C?7500:a.B?1E3*a.B.interval:a.g.fa().heartbeatInterval||6E4:1E3),a.o=g.DD((0,g.z)(a.bT,a),b)}},Kxa=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=Jxa(c),f=a.g.fa();
if(g.TT(a.g).kb()&&!g.zN(f)&&!a.g.isPeggedToLive()&&!d)return e;var k=(d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint)&&d.videoId;if(k)return g.U0(a.g.app,k,void 0,void 0,!0,!0,d),e;if("OK"==b.status.toUpperCase()){if(!f.hlsvp&&!f.ae||a.A&&c&&c.broadcastId!=a.A.liveStreamability.liveStreamabilityRenderer.broadcastId)return c={video_id:f.videoId},f.isLiveDestination&&(c.is_live_destination="1"),a.g.qo(c),e;g.lU(a.g,"heartbeat")}return e},Jxa=function(a){var b=0;
a&&a.pollDelayMs&&(a=(0,window.parseInt)(a.pollDelayMs,10))&&(b=a);return b},G6=function(a,b,c){if(a.o){a.o=window.NaN;
a.J++;var d=a.g.fa();(d.heartbeatSoftFail?0:a.J>=(a.B?a.B.g:d.heartbeatRetries||5))?(b=b?"heartbeat.net":"heartbeat.servererror",d=(d=a.g.fa())&&d.wa?g.U("YTP_ERROR_STREAM_LICENSE_NOT_FOUND"):g.U("YTP_ERROR_LICENSE"),g.SS(a.g.app.A,b,d,c)):D6(a)}},H6=function(a){a.J=0;
a.o&&(g.FD(a.o),a.o=window.NaN);a.G=!1},Mxa=function(a){try{return g.Uw(a)}catch(b){return null}};g.p(z6,g.X);
z6.prototype.D=function(){this.A||(this.A=new g.$F(g.W(this.C).rg));var a={context:g.NF(this.A.g)};if(this.o.isToggled){a.params=this.o.toggledServiceEndpoint.removeUpcomingEventReminderEndpoint.params;var b="notification/remove_upcoming_event_reminder"}else a.params=this.o.defaultServiceEndpoint.addUpcomingEventReminderEndpoint.params,b="notification/add_upcoming_event_reminder";var c={timeout:5E3};c.onError=(0,g.z)(this.B,this);c.sd=(0,g.z)(this.B,this);g.OF(this.A,b,a,c);this.o.isToggled=!this.o.isToggled;
A6(this)};
z6.prototype.B=function(){this.o&&(this.o.isToggled=!this.o.isToggled,A6(this))};g.p(B6,g.X);
B6.prototype.D=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.o=a;b.liveStreamOfflineSlateRenderer.canShowCountdown?this.F():C6(this,b.liveStreamOfflineSlateRenderer);var c=this.element;if(b&&b.liveStreamOfflineSlateRenderer&&b.liveStreamOfflineSlateRenderer.scheduledStartTime){var d=b.liveStreamOfflineSlateRenderer.scheduledStartTime-(0,g.H)()/1E3;d=86400>=d&&86340<d}else d=!1;g.T(c,"ytp-offline-slate-show-final-day",d);if(c=a&&a.liveStreamability&&
a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail){d=0;for(var e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage=
"";b.liveStreamOfflineSlateRenderer.actionButtons?(this.B||(this.B=new z6(this.A),this.B.Da(this.sa["ytp-offline-slate-buttons"]),g.N(this,this.B)),Hxa(this.B,b.liveStreamOfflineSlateRenderer.actionButtons[0])):this.B&&Hxa(this.B,null);this.o=a}else this.o=null;this.G()};
B6.prototype.G=function(){var a=g.TT(this.A),b=this.A.fa(),c=b.wa&&(g.nO(a)||g.V(a,2)||g.V(a,64));a=a.kb()&&!g.zN(b)&&!this.A.isPeggedToLive(!0);c&&!a&&this.o&&"LIVE_STREAM_OFFLINE"==this.o.status.toUpperCase()?this.g||(this.show(),this.A.T("offlineslatestatechange")):this.g&&(this.hide(),this.A.T("offlineslatestatechange"))};
B6.prototype.F=function(){var a=this.o&&this.o.liveStreamability&&this.o.liveStreamability.liveStreamabilityRenderer&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.H)()/1E3),c=a.canShowCountdown&&(0,window.parseInt)(a.scheduledStartTime,10);!c||c<=b?(C6(this,a),this.C.stop()):(b=g.sV(c-b),C6(this,a,b),g.Ot(this.C))}};
B6.prototype.V=function(){this.C.dispose();this.C=null;g.X.prototype.V.call(this)};g.p(E6,g.uU);g.h=E6.prototype;g.h.V=function(){H6(this);g.kU(this.g,"heartbeat");g.uU.prototype.V.call(this)};
g.h.GK=function(){this.I=!0;D6(this,2E3)};
g.h.HK=function(a){this.B=a;D6(this,2E3)};
g.h.IK=function(a){g.V(a.state,2)||g.V(a.state,64)?(H6(this),this.C&&(this.I=!0,D6(this,1E3))):(g.V(a.state,1)||g.V(a.state,8))&&D6(this,2E3)};
g.h.TR=function(){3!==this.g.Ra()&&D6(this,2E3)};
g.h.bT=function(){var a=g.W(this.g),b=this.g.fa();var c=a.baseYtUrl;if(3==this.g.Ra())this.o=window.NaN;else if(g.V(g.TT(this.g),4))this.o=window.NaN;else if(F6(this)||b.wa){if(!Lxa(this)||b.wa){var d="GET";var e=a.o;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.mg,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.forcedExperiments,utc_offset_minutes:this.L};(e=g.lN(b))&&(a.uloc=e);(e=this.g.xh().ingestionTime)&&
(a.ingestion_time=e);c=g.Mg(c+"heartbeat",a)}else d="GET",c=g.Mg(this.B.url,{request_id:g.sL()}),b.mg&&(c=g.Mg(c,{vvt:b.mg}),b.mdxEnvironment&&(c=g.Mg(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Mg(c,{access_token:b.oauthToken}));b.al&&(c=g.Mg(c,{internalipoverride:b.al}));b.innertubez&&(c=g.Mg(c,{innertubez:b.innertubez}));c=g.Mg(c,{cpn:b.clientPlaybackNonce});g.TD(c,{format:"RAW",method:d,timeout:3E4,Jb:(0,g.z)(this.OJ,this),onError:(0,g.z)(this.NJ,this),sd:(0,g.z)(this.PJ,this),
withCredentials:!0})}else H6(this)};
g.h.OJ=function(a){if(this.o){a=a.responseText;var b=Mxa(a);if(b){this.g.ua("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(Nxa))?"0"==c[1]?0:1:-1;if(-1==c)G6(this,!1,"decode");else if(2!=c||F6(this))if(this.J=0,this.o=window.NaN,1==c){this.G=!1;b=this.g;c="YTP_ERROR_LICENSE";var d=Mxa(a);d?a=d.reason||g.U(c):((a=a.match(Nxa))&&(a=(0,window.parseInt)(a[1],10))&&(c=g.JN(a)),a=g.U(c));g.SS(b.app.A,"heartbeat.stop",
a,void 0)}else this.G=!0,a=0,this.C&&b&&(a=Kxa(this,b),this.g.T("livestatedata",b)),a?D6(this,a):D6(this);else H6(this),this.G=!0}};
g.h.NJ=function(a){G6(this,!0,"net-"+a.status)};
g.h.PJ=function(){G6(this,!0,"timeout")};
g.h.FK=function(){return!!this.F&&this.F.g};
var Nxa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.CY.heartbeat=E6;})(_yt_player);
